name: Dr Ranjana Srivastava
favicon: null
layout_spectrum: 0.76331
typography_spectrum: 0.61024
title: 'Dr Ranjana Srivastava: Award-winning writer, broadcaster and oncologist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#d42830'
    - '#020202'
    - '#2a669e'
    - '#a3a3a3'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
