name: drranjanasrivastava
favicon: null
layout_spectrum: 0.959525057580322
typography_spectrum: 0.3387488527223468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8384506253059953
  lightness: 0.16533042141236365
  saturation: 0.11218078201636672
  rhythmicContrast: 0.42297058063559234
purpose: []
