layout_spectrum: 0.7977379523217678
typography_spectrum: 0.47403550473973155
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.011738172732293606
  lightness: 0.6946048543322831
  saturation: 0.5571587898302823
  rhythmicContrast: 0.5003860720898956
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-83191934-1
  facebook: null
  twitter: null
author:
  name: Ranjana Srivastava
  email: feedbacksriv@gmail.com
logo: null
name: Dr Ranjana Srivastava
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: 9447860f-2625-49f0-ac35-b535c6e5a1ba
    type: content
  - name: Contact
    id: f9af1fe5-36ca-425f-b22f-fe4874dac352
    type: content
  - name: Books
    id: b6580ab8-3fe8-4b85-8d2a-ff9c8d241d35
    type: content
  - name: Audio Highlights
    id: a570aa87-fbbe-42a3-8476-152c71daa1fb
    type: content
  - name: NEJM articles
    id: 116f95a4-5111-4d62-b097-6fe3e8804094
    type: content
  - name: Video Highlights
    id: 3b90d9f0-3e14-48fe-b4c4-1ae39e6f39ef
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6b034ed8-66a3-4525-99d9-f153fc5ea7be.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Dr Ranjana Srivastava
description: 'Fulbright Scholar, Oncologist, Writer & Broadcaster'
purpose: []
