name: drranjanasrivastava
favicon: null
layout_spectrum: 0.95788
typography_spectrum: 0.50542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf1f4'
    - '#006599'
    - '#9acefe'
    - '#000102'
    - '#77a155'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
