typography_spectrum: 0.674143749056384
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.6906950508709997
  lightness: 0.30970555753447115
  saturation: 0.9436941822059453
  rhythmicContrast: 0.6321642177645117
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7922928428743035
analytics:
  google: UA-83191934-1
  facebook: null
  twitter: null
name: Dr Ranjana Srivastava
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6b034ed8-66a3-4525-99d9-f153fc5ea7be.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Dr Ranjana Srivastava
description: 'Fulbright Scholar, Oncologist, Writer & Broadcaster'
purpose: []
