layout_spectrum: 0.34531086403876543
typography_spectrum: 0.9666787716560066
color:
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
  brandStrength: 0.24171963473781943
  lightness: 0.3779756131116301
  saturation: 0.9641232322901487
  rhythmicContrast: 0.03122591250576079
name: Dr Ranjana Srivastava
favicon: null
title: 'Dr Ranjana Srivastava: Fulbright Scholar, writer, broadcaster and oncologist'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
