name: Dr Ranjana Srivastava
favicon: null
layout_spectrum: 0.51226
typography_spectrum: 0.61024
title: 'Dr Ranjana Srivastava: Award-winning writer, broadcaster and oncologist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf1f4'
    - '#006599'
    - '#9acefe'
    - '#000102'
    - '#77a155'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
