name: drranjanasrivastava
favicon: null
layout_spectrum: 0.89399
typography_spectrum: 0.80954
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dad9c5'
    - '#bd8c75'
    - '#1c1618'
    - '#c93042'
    - '#5a4854'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0.42297058063559234
purpose: []
