layout_spectrum: 0.8406360591761768
typography_spectrum: 0.08789020497351885
color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 0.38994401623494923
  lightness: 0.8057638271711767
  saturation: 0.8810133810620755
  rhythmicContrast: 0.8673591602127999
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-83191934-1
  facebook: null
  twitter: null
author:
  name: Ranjana Srivastava
  email: feedbacksriv@gmail.com
logo: null
name: Dr Ranjana Srivastava
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6b034ed8-66a3-4525-99d9-f153fc5ea7be.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Dr Ranjana Srivastava
description: 'Fulbright Scholar, Oncologist, Writer & Broadcaster'
purpose: []
