name: Dr Ranjana Srivastava
favicon: null
layout_spectrum: 0.61557
typography_spectrum: 1
title: 'Dr Ranjana Srivastava: Award-winning writer, broadcaster and oncologist'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#d42830'
    - '#020202'
    - '#2a669e'
    - '#a3a3a3'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
