name: drranjanasrivastava
favicon: null
layout_spectrum: 0.70033
typography_spectrum: 0.81621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.42297058063559234
purpose: []
