name: drranjanasrivastava
favicon: null
layout_spectrum: 0.89399
typography_spectrum: 0.80954
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0.42297058063559234
purpose: []
